### ISSUE TITLE
`BlockWhenFull=True` Produces a lot of threadpool threads fast when blocked

### ISSUE THREAD

**Issue by AntonSmolkov** [manigandham/serilog-sinks-fastconsole#9]
With `BlockWhenFull=True`, when a lot of tasks try to write logs simultaneously, and `QueueLimit` is exhausted, there is a massive and fast  grow of the amount of threads. 
It looks like new threads creation is not even being throttled by thread pool. (not sure though)

At the same time, this is not the case for [Serilog.Sinks.Async](https://github.com/serilog/serilog-sinks-async/tree/dev/src/Serilog.Sinks.Async) (with the same settings) which uses BlockingCollection.

I think this [line of code](https://github.com/manigandham/serilog-sinks-fastconsole/blob/0c130326fe49eedbb182d6f8e7cccbbe511f32ea/src/Serilog.Sinks.FastConsole/FastConsoleSink.cs#L41) is the reason.

I also made some experiments  which prove my suggestion: 

```C#
using System.Collections.Concurrent;
using System.Diagnostics;
using System.Threading.Channels;

var lockObject = new object();
var blockingCollection = new BlockingCollection<int>(10);
var channel = Channel.CreateBounded<int>(new BoundedChannelOptions(10) {SingleReader = true});

var cts = new CancellationTokenSource();
cts.CancelAfter(30000);

while (!cts.IsCancellationRequested)
{
    Task.Run(() =>
    {
        //channel.Writer.WriteAsync(0).AsTask().GetAwaiter().GetResult(); // Result - 147 threads
        //blockingCollection.Add(0);  //Result - 52 threads
        //lock (lockObject) { channel.Writer.WriteAsync(0).AsTask().GetAwaiter().GetResult(); } //Result - 56 threads
        //var j = 1 + 1; // Result - 15 threads
    });
}
Console.WriteLine(Process.GetCurrentProcess().Threads.Count);
```

Why is this a problem?  (just in case)
1. Thread is an expensive OS resource with it's own pid, stack, context, etc
2. Total amount of threads can be limited in some environments ([OpenShift - 1024](https://computingforgeeks.com/change-pids-limit-value-in-openshift/)). Exceeding this limits can cause application crash.

**Comment by leotsarev** [comment]
Probable case https://github.com/dotnet/runtime/pull/53471

**Comment by AntonSmolkov** [comment]
> Probable case [dotnet/runtime#53471](https://github.com/dotnet/runtime/pull/53471)

Yes, thank you!
Toub also mentioned about this new optimization here - 
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#threading

Looks like in our case, simple lock must be added before synk-over-async operation

**Comment by manigandham** [comment]
hey @AntonSmolkov 

Replying to your code comments here:

https://github.com/manigandham/serilog-sinks-fastconsole/commit/b16aeba1c70b1fe99ffba625397f21bdf2979d97#commitcomment-93146833

> LongRunning option won’t help, here is the explanation
> http://blog.i3arnon.com/2015/07/02/task-run-long-running/

The `LongRunning` flag still starts a new thread if the threadpool is full and is what the [Serilog Async library uses](https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs#L27) so I'm leaning on their code.

https://github.com/manigandham/serilog-sinks-fastconsole/commit/b16aeba1c70b1fe99ffba625397f21bdf2979d97#commitcomment-93147075

> Task.Run(() => _queue.Writer.WriteAsync(logEvent)).ConfigureAwait(false).GetAwaiter().GetResult();
> Looks like moving queued items to infinite task queue.

The task queue is not infinite, it still blocks the thread on the result of the async operation, however this offloads the `WriteAsync` call to the threadpool. It's one of the major workarounds when encountering sync-over-async, as recommended by Stephen Cleary: https://learn.microsoft.com/en-us/archive/msdn-magazine/2015/july/async-programming-brownfield-async-development#the-thread-pool-hack

**Comment by manigandham** [comment]
hey @AntonSmolkov, replying to all of your comments here:

- https://github.com/manigandham/serilog-sinks-fastconsole/commit/b16aeba1c70b1fe99ffba625397f21bdf2979d97#commitcomment-93146833

  > LongRunning option won’t help, here is the explanation
  > http://blog.i3arnon.com/2015/07/02/task-run-long-running/

The `LongRunning` flag still starts a new thread if the threadpool is full and is what the [Serilog Async library uses](https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs#L27) so I'm leaning on their code.

- https://github.com/manigandham/serilog-sinks-fastconsole/commit/b16aeba1c70b1fe99ffba625397f21bdf2979d97#commitcomment-93147075

  > Task.Run(() => _queue.Writer.WriteAsync(logEvent)).ConfigureAwait(false).GetAwaiter().GetResult();
  > Looks like moving queued items to infinite task queue.

The task queue is not infinite, it still blocks the thread on the result of the async operation, however this offloads the `WriteAsync` call to the threadpool. It's one of the major workarounds when encountering sync-over-async, as recommended by Stephen Cleary: https://learn.microsoft.com/en-us/archive/msdn-magazine/2015/july/async-programming-brownfield-async-development#the-thread-pool-hack

- https://github.com/manigandham/serilog-sinks-fastconsole/issues/9#issuecomment-1352643718

  > > Probable case [dotnet/runtime#53471](https://github.com/dotnet/runtime/pull/53471)
  > 
  > Yes, thank you! Toub also mentioned about this new optimization here - https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/#threading
  > 
  > Looks like in our case, simple lock must be added before synk-over-async operation

A lock is not the correct solution as it adds severe contention. This library was specifically made to avoid any kind of locking (like that found in the typical console output). Since blocking the threads for a full buffer was a requested feature, the blocking should only happen on each individual write call waiting on the buffer instead of a serialized lock for all writes.

**Comment by manigandham** [comment]
The recent updates has fixed any threadpool issues in my testing, it can be checked with the next commit that updates the demo app with stats on the timing and thread in process: https://github.com/manigandham/serilog-sinks-fastconsole/commit/80bf7195d1d583662e8fbf1400379a5e284cf98b

@AntonSmolkov please retry using that app so that it compares the entire library and sink.

**Comment by AntonSmolkov** [comment]
Hi, @manigandham, thank you for the answer.

> The LongRunning flag still starts a new thread if the threadpool is full and is what the [Serilog Async library uses](https://github.com/serilog/serilog-sinks-async/blob/dev/src/Serilog.Sinks.Async/Sinks/Async/BackgroundWorkerSink.cs#L27) so I'm leaning on their code.

Indeed new thread will be started, but code after very first ‘await’ will go to threadpool anyway(see article i mentioned).  Serilog.Sinks.Async uses it, but they have only synchronous code on their ‘pump()’ method, so it works for them.

> The task queue is not infinite, it still blocks the thread on the result of the async operation, however this offloads the WriteAsync call to the threadpool.

In this case (‘BlockWhenFull=True’) threads must be blocked on buffer which is full. With ‘Task.Run()’, another buffer for logs is effectively created in front of the main one, but this time it’s located on task queue.

> A lock is not the correct solution as it adds severe contention. This library was specifically made to avoid any kind of locking (like that found in the typical console output). Since blocking the threads for a full buffer was a requested feature, the blocking should only happen on each individual write call waiting on the buffer instead of a serialized lock for all writes.

I agree that avoiding locks as match as possible is a good practice. But here i propose using it only in case if buffer is full and BlockWhenFull=True. Threads must be blocked anyway in this case. Bounded Channel , which is used for buffering, contains ~~[the same lock() ](https://github.com/dotnet/runtime/blob/v6.0.12/src/libraries/System.Threading.Channels/src/System/Threading/Channels/BoundedChannel.cs) underneath anyway~~ , but putting another lock() in front of it would help to bypass thread-poll optimization  mentioned earlier. 

Update: 
Not actually the same, seems like Channels's internal locking mechanics would work more efficiently, if many slots are becoming available simultaneously. But still can't figure out better approach to avoid this threads flooding🤔

**Comment by manigandham** [comment]
@AntonSmolkov 

> Indeed new thread will be started, but code after very first ‘await’ will go to threadpool anyway(see article i mentioned). Serilog.Sinks.Async uses it, but they have only synchronous code on their ‘pump()’ method, so it works for them.

It's the same issue here with synchronous code calling async methods.

> In this case (‘BlockWhenFull=True’) threads must be blocked on buffer which is full. With ‘Task.Run()’, another buffer for logs is effectively created in front of the main one, but this time it’s located on task queue.

After further testing I've removed this.

> I agree that avoiding locks as match as possible is a good practice. But here i propose using it only in case if buffer is full and BlockWhenFull=True. Threads must be blocked anyway in this case. Bounded Channel , which is used for buffering, contains the same lock() underneath anyway, but putting another lock() in front of it would help to bypass thread-poll optimization mentioned earlier.

Locks aren't necessary, the threads will be blocked by the underlying `System.Threading.Channel` writer based on its settings. The issue you're describing is part of the runtime and should be handled by configuring your specific application and environment. This library should follow best practices (for sync-over-async as needed) instead of trying to go against the threadpool changes made by the .NET team.

If you do need to configure your threadpool settings, you can do so as documented here: https://learn.microsoft.com/en-us/dotnet/core/runtime-config/threading#thread-injection-in-response-to-blocking-work-items

**Comment by AntonSmolkov** [comment]
> It's the same issue here with synchronous code calling async methods.

Not actually completely the same, but anyway this fact doesn’t make this `Task.Factory.StartNew` useful. 

> If you do need to configure your threadpool settings, you can do so as documented here:

Didn’t know about this settings, thanks!
